name: Tests

# Run on
on:
  push:
    # any branch
    branches:
      - '*'
jobs:
  tests:
    name: Install And Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install NPM dependencies
        run: npm install

      - name: Start the Docker testing environment
        run: npm run env start --xdebug=coverage

      - name: Ensure uploads dir exists first
        run: mkdir -p wordpress/wp-content/uploads

      - name: Test
        run: npm run test:php
